config/routes.rb
SampleApp110811::Application.routes.draw do
  resources :products
  resources :product_groups

  resources :offers

  resources :users
  resources:sessions, :only=> [:new, :create, :destroy]

  root :to => 'pages#application'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signout', :to => 'sessions#destroy'
  match '/home', :to => 'pages#home'
  match '/newoffer', :to => 'offers#new'
  match '/newprodgrp', :to => 'products#new'
  match '/newprodgroup', :to => 'product_groups#new'
  match '/signin', :to => 'sessions#create'
  match '/prodgrpind', :to => 'product_groups#index'

end

app/models/product_group.rb
class ProductGroup < ActiveRecord::Base
  belongs_to :offer
  belongs_to :product
end

app/controllers/product_groups_controller.rb
class ProductGroupsController < ApplicationController
  # GET /product_groups
  # GET /product_groups.json
  def index
    @product_groups = ProductGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @product_groups }
    end
  end

  # GET /product_groups/1
  # GET /product_groups/1.json
  def show
    @product_group = ProductGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product_group }
    end
  end

  # GET /product_groups/new
  # GET /product_groups/new.json
  def new
    @product_group = ProductGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product_group }
    end
  end

  # GET /product_groups/1/edit
  def edit
    @product_group = ProductGroup.find(params[:id])
  end

  # POST /product_groups
  # POST /product_groups.json
  def create
    @product_group = ProductGroup.new(params[:product_group])

    respond_to do |format|
      if @product_group.save
        format.html { redirect_to @product_group, :notice => 'Product group was successfully created.' }
        format.json { render :json => @product_group, :status => :created, :location => @product_group }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /product_groups/1
  # PUT /product_groups/1.json
  def update
    @product_group = ProductGroup.find(params[:id])

    respond_to do |format|
      if @product_group.update_attributes(params[:product_group])
        format.html { redirect_to @product_group, :notice => 'Product group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /product_groups/1
  # DELETE /product_groups/1.json
  def destroy
    @product_group = ProductGroup.find(params[:id])
    @product_group.destroy

    respond_to do |format|
      format.html { redirect_to product_groups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/product_groups_helper.rb
module ProductGroupsHelper
end

app/views/product_groups/_form.html.erb
<%= form_for(@product_group) do |f| %>
  <% if @product_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_group.errors.count, "error") %> prohibited this product_group from being saved:</h2>

      <ul>
      <% @product_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <center>
						<div id="newuser_border" class="radius_super">
							<div id="login_panel" class="radius_big">
								<table width="100px">
									<tr>
										
									</tr>

  <div class="index_label" >
    <%= f.label :prodgrpid %><br />
    <%= f.number_field :prodgrpid %>
  </div>
  <div class="index_label" >
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Product Group', :class => 'button' %>
  </div>
<% end %>

app/views/product_groups/edit.html.erb
<h1>Editing product_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_group %> |
<%= link_to 'Back', product_groups_path %>

app/views/product_groups/index.html.erb
<!DOCTYPE html>
<head>
  <%@title = "HOME"%>
  <%= render 'layouts/stylesheets' %>
  <%= csrf_meta_tags %>
  
  
  
  <div id="welcome_word"><h2>
    Welcome <span class="blue"><%= current_user.name%></span>, create your new offer <span class="red bold"></span> down below:</h2></div>
    
    <div id="logout"> <%= link_to 'Logout',  '/signout', :class => 'button' %></div>  
 
<title>Home</title>
</head>

<body>
 <%= stylesheet_link_tag 'home_style.css', :media => 'screen' %>
 <%= stylesheet_link_tag 'index_style.css', :media => 'screen' %>

  <div id="nav_bar">
  
    <table id="search_table">
      <tr>
        <td width="160px" height="30px"></td>
        <td style="padding-right: 10px"><input type="text" id="search_field" value=""></td>

        <td width="100px" style="padding-left: 5px"><input type="submit" id="search_submit" class="button" value="Search" /></td>
        <td width="200px"></td>
      </tr>
    </table>
  </div>
</div>
<div id="container">
  <table width="100%">
    <tr>
      <td width="150px" valign="top"><div id="left">
<%= image_tag('logo_50.png') %>
          <div id="sidebar_border">
            <div id="sidebar">
              <ul id="menu_ul">
                <!-- <div id="chtsht_div">
<div class="li_border"><li class="menu_li"> <a link="#">My Cheetsheet</a></li></div>
</div> -->
                
                    <div class="button_white"><li class="menu_li"> <a href="/newoffer">New Offer</a></li></div>
                    <div class="button_white"><li class="menu_li"> <a href="/prodgrpind">Product Groups</a></li></div>
                    <div class="button_white"><li class="menu_li"> <a href="/home">Last Seven Days</a></li></div>
                    <div class="button_white"><li class="menu_li"> <a href="/home">Last 30 Days</a></li></div>
                    <div class="button_white"><li class="menu_li"> <a href="/home">Last 90 Days</a></li></div>
                   
                   
                  </ul>
               
             
              </ul>
            </div>
          </div>
        </div></td>
      <td valign="top"><div id="right"><span class="blue">
    Product Group Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    Product Group ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
  
      <% @product_groups.each do |product_group| %>
 <div class="button_white_long"><li class="menu_li"> <a href="<%= edit_product_group_path(product_group) %>">
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= product_group.name %>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=product_group.prodgrpid %>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= link_to 'Show',  product_group, :class => 'button' %>
      <%= link_to 'Edit', edit_product_group_path(product_group), :class => 'button' %>
     <%= link_to 'Destroy', product_group, :class => 'button' ,:confirm => 'Are you sure?', :method => :delete %></div>
    

 </a></li></div>
 
  <% end %>
      

                  </div></td>
                  
    <div id="right_container"> </div>
  </td>
    </tr>
 

</table>
</div>

<br />
<center><%= link_to 'Create New Product Group', new_product_group_path, :class => 'button' %></center>

</body>

app/views/product_groups/new.html.erb
<!DOCTYPE html>
<head>
  <%@title = "HOME"%>
  <%= render 'layouts/stylesheets' %>
  <%= csrf_meta_tags %>
  
  
  
    <div id="welcome_word"><h2>
    Welcome <span class="blue"><%= current_user.name%></span>, create your new offer <span class="red bold"></span> down below:</h2></div>
   <div id="logout"> <%= link_to 'Logout',  '/signout', :class => 'button' %></div>
   
<title>New Product Group</title>
</head>

<body>
 <%= stylesheet_link_tag 'home_style.css', :media => 'screen' %>
 <%= stylesheet_link_tag 'index_style.css', :media => 'screen' %>

  <div id="nav_bar">
  	
    <table id="search_table">
      <tr>
        <td width="160px" height="30px"></td>
        <td style="padding-right: 10px"><input type="text" id="search_field" value=""></td>

        <td width="100px" style="padding-left: 5px"><input type="submit" id="search_submit" class="button" value="Search" /></td>
        <td width="200px"></td>
      </tr>
    </table>
  </div>
</div>
<div id="container">
  <table width="100%">
    <tr>
      <td width="150px" valign="top"><div id="left">
<%= image_tag('logo_50.png') %>
          <div id="sidebar_border">
            <div id="sidebar">
              <ul id="menu_ul">
                <!-- <div id="chtsht_div">
                  <div class="li_border"><li class="menu_li"> <a link="#">My Cheetsheet</a></li></div>
                </div> -->
                
                    <div class="button_white"><li class="menu_li"> <a href="/newoffer">New Offer</a></li></div>
                    <div class="button_white"><li class="menu_li"> <a href="/prodgrpind">Product Groups</a></li></div>
                    <div class="button_white"><li class="menu_li"> <a href="/home">Last Seven Days</a></li></div>
                    <div class="button_white"><li class="menu_li"> <a href="/home">Last 30 Days</a></li></div>
                    <div class="button_white"><li class="menu_li"> <a href="/home">Last 90 Days</a></li></div>
                   
                  </ul>
               
             
              </ul>
            </div>
          </div>
        </div></td>
      <td valign="top"><div id="left">
      	<%= render 'form' %>

<%= link_to 'Back', home_path %>
                  </div></td>
                  
    <div id="right_container"> </div>
  </td>
    </tr>
 

</table>
</div>

<br/>


</body>

app/views/product_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Prodgrpid:</b>
  <%= @product_group.prodgrpid %>
</p>

<p>
  <b>Name:</b>
  <%= @product_group.name %>
</p>


<%= link_to 'Edit', edit_product_group_path(@product_group) %> |
<%= link_to 'Back', product_groups_path %>