config/routes.rb
SampleApp110811::Application.routes.draw do
  resources :products
  resources :product_groups

  resources :offers

  resources :users
  resources:sessions, :only=> [:new, :create, :destroy]

  root :to => 'pages#application'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signout', :to => 'sessions#destroy'
  match '/home', :to => 'pages#home'
  match '/newoffer', :to => 'offers#new'
  match '/newprodgrp', :to => 'products#new'
  match '/newprodgroup', :to => 'product_groups#new'
  match '/signin', :to => 'sessions#create'
  match '/prodgrpind', :to => 'product_groups#index'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  has_many :product_group
  def product_drop
    @product_groups = ProductGroup.all
    return @product_groups
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
    @product_groups = ProductGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @offers }
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @offer = Offer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @offer }
    end
  end

  # GET /offers/new
  # GET /offers/new.json
  def new
    @offer = Offer.new
    @product_groups = ProductGroup.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @offer }
    end
  end

  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
    @product_groups = ProductGroup.all
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(params[:offer])

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, :notice => 'Offer was successfully created.' }
        format.json { render :json => @offer, :status => :created, :location => @offer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @offer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.json
  def update
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to @offer, :notice => 'Offer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @offer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>
			<center>
						<div id="newuser_border" class="radius_super">
							<div id="login_panel" class="radius_big">
								<table width="100px">
									<tr>
										
									</tr>
  <div class="index_label" >
  	
    <%= f.label 'Product Groups' %><br />
    <%= f.collection_select(:prodgrpid, @product_groups, :prodgrpid, :name, :prompt => true)%>
    
  </div>
  <div class="index_label" >
    <%= f.label 'Start Date'%><br />
    <%= f.text_field :sDate %>
  </div>
  <div class="index_label" >
    <%= f.label 'End Date' %><br />
    <%= f.text_field :eDate %>
  </div>
 <div class="index_label" >
    <%= f.label 'Offer Name' %><br />
    <%= f.text_field :Name %>
  </div>
 <div class="index_label" >
    <%= f.label :Status %><br />
    <%= f.select(:Status, [['Testing'], ['Deployed']]) %>
    
  </div>
  <div class="actions">
    <%= f.submit 'Create New Offer', :class => 'button' %>
  </div>
  </div>
 </center>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<h1>Listing offers</h1>

<table>
  <tr>
    <th>Prodgrpid</th>
    <th>Sdate</th>
    <th>Edate</th>
    <th>Name</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offers.each do |offer| %>
  <tr>
    <td><%= offer.prodgrpid %></td>
    <td><%= offer.sDate %></td>
    <td><%= offer.eDate %></td>
    <td><%= offer.Name %></td>
    <td><%= offer.Status %></td>
    <td><%= link_to 'Show', offer %></td>
    <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
    <td><%= link_to 'Destroy', offer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<!DOCTYPE html>
<head>
  <%@title = "HOME"%>
  <%= render 'layouts/stylesheets' %>
  <%= csrf_meta_tags %>
  
  
  
    <div id="welcome_word"><h2>
    Welcome <span class="blue"><%= current_user.name%></span>, create your new offer <span class="red bold"></span> down below:</h2></div>
   
 <div id="logout"> <%= link_to 'Logout',  '/signout', :class => 'button' %></div>

<title>New Offer</title>
</head>

<body>
 <%= stylesheet_link_tag 'home_style.css', :media => 'screen' %>
 <%= stylesheet_link_tag 'index_style.css', :media => 'screen' %>

  <div id="nav_bar">
  	
    <table id="search_table">
      <tr>
        <td width="160px" height="30px"></td>
        <td style="padding-right: 10px"><input type="text" id="search_field" value=""></td>

        <td width="100px" style="padding-left: 5px"><input type="submit" id="search_submit" class="button" value="Search" /></td>
        <td width="200px"></td>
      </tr>
    </table>
  </div>
</div>
<div id="container">
  <table width="100%">
    <tr>
      <td width="150px" valign="top"><div id="left">
<%= image_tag('logo_50.png') %>
          <div id="sidebar_border">
            <div id="sidebar">
              <ul id="menu_ul">
                <!-- <div id="chtsht_div">
                  <div class="li_border"><li class="menu_li"> <a link="#">My Cheetsheet</a></li></div>
                </div> -->
                
               <div class="button_white"><li class="menu_li"> <a href="/newoffer">New Offer</a></li></div>
                    <div class="button_white"><li class="menu_li"> <a href="/prodgrpind">Product Groups</a></li></div>
                    <div class="button_white"><li class="menu_li"> <a href="/home">Last Seven Days</a></li></div>
                    <div class="button_white"><li class="menu_li"> <a href="/home">Last 30 Days</a></li></div>
                    <div class="button_white"><li class="menu_li"> <a href="/home">Last 90 Days</a></li></div>
                   
                  </ul>
               
             
              </ul>
            </div>
          </div>
        </div></td>
      <td valign="top"><div id="left">
      	<%= render 'form' %>

<%= link_to 'Back', home_path %>
                  </div></td>
                  
    <div id="right_container"> </div>
  </td>
    </tr>
 

</table>
</div>

<br/>


</body>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Prodgrpid:</b>
  <%= @offer.prodgrpid %>
</p>

<p>
  <b>Sdate:</b>
  <%= @offer.sDate %>
</p>

<p>
  <b>Edate:</b>
  <%= @offer.eDate %>
</p>

<p>
  <b>Name:</b>
  <%= @offer.Name %>
</p>

<p>
  <b>Status:</b>
  <%= @offer.Status %>
</p>


<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>