config/routes.rb
SampleApp110811::Application.routes.draw do
  resources :products
  resources :product_groups

  resources :offers

  resources :users
  resources:sessions, :only=> [:new, :create, :destroy]

  root :to => 'pages#application'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'
  match '/signout', :to => 'sessions#destroy'
  match '/home', :to => 'pages#home'
  match '/newoffer', :to => 'offers#new'
  match '/newprodgrp', :to => 'products#new'
  match '/newprodgroup', :to => 'product_groups#new'
  match '/signin', :to => 'sessions#create'
  match '/prodgrpind', :to => 'product_groups#index'

end

app/views/layouts/_footer.html.erb
 <footer>
	<nav class = "round" >
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "News", 'http://news.railstutorial.org' %></li>
			<li><%= link_to "Rails tutorial", 'http://railstutorial.org' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<nav class ="round" >
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
			<li><%= link_to "Sign in", new_session_path %> </li>
	    </ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--<%= stylesheet_link_tag    'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag    'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag    'custom', :media => 'screen' %>-->
<%= stylesheet_link_tag    'global_style', :media => 'screen' %>
<%= stylesheet_link_tag    'index_style', :media => 'screen' %>